version: "3.9"

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db

  express:
    build:
      context: .
      target: production
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    depends_on:
      - mongo

volumes:
  mongo: {}
