version: "3.9"

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - 2717:27017

  express:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://mongo:27017
      DB_NAME: test_db
    command: yarn run dev
    depends_on:
      - mongo

volumes:
  mongo: {}
